services:
  app:
    build: ./docker/php
    container_name: painter_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - mailhog

  web:
    image: nginx:alpine
    container_name: painter_nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: painter_db
    environment:
      MYSQL_DATABASE: painter_matching
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  vite:
    image: node:20-alpine
    container_name: painter_vite
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - /var/www/html/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - app

  mailhog:
    image: mailhog/mailhog:latest
    container_name: painter_mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port

volumes:
  db-data: